package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import DAO.Despachos.Abogados.AbogadosDAO;
import DAO.Despachos.Abogados.AbogadosDAOimpl;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Abogados generated by hbm2java
 */
@Entity
@Table(name="abogados"
    ,catalog="despachoabogados"
)
public class Abogados  implements java.io.Serializable {


     private Integer idAbogado;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String noCarne;
     private String cedula;
     private String direccion;
     private Integer telefono;
     private Integer celular;
     private String email;
     private Set abogadoTipoabogados = new HashSet(0);
     private AbogadosDAO dao;

    public Abogados() {
        dao = new AbogadosDAOimpl();
        
    }

    public Abogados(String nombre, String primerApellido, String noCarne, String cedula, String direccion) {
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.noCarne = noCarne;
        this.cedula = cedula;
        this.direccion = direccion;
    }
    public Abogados(String nombre, String primerApellido, String segundoApellido, String noCarne, String cedula, String direccion, Integer telefono, Integer celular, String email, Set abogadoTipoabogados) {
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.noCarne = noCarne;
       this.cedula = cedula;
       this.direccion = direccion;
       this.telefono = telefono;
       this.celular = celular;
       this.email = email;
       this.abogadoTipoabogados = abogadoTipoabogados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAbogado", unique=true, nullable=false)
    public Integer getIdAbogado() {
        return this.idAbogado;
    }
    
    public void setIdAbogado(Integer idAbogado) {
        this.idAbogado = idAbogado;
    }
    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="primerApellido", nullable=false, length=45)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    
    @Column(name="segundoApellido", length=45)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    
    @Column(name="noCarne", nullable=false, length=20)
    public String getNoCarne() {
        return this.noCarne;
    }
    
    public void setNoCarne(String noCarne) {
        this.noCarne = noCarne;
    }
    
    @Column(name="cedula", nullable=false, length=15)
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    
    @Column(name="direccion", nullable=false, length=100)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular")
    public Integer getCelular() {
        return this.celular;
    }
    
    public void setCelular(Integer celular) {
        this.celular = celular;
    }
    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="abogados")
    public Set getAbogadoTipoabogados() {
        return this.abogadoTipoabogados;
    }
    
    public void setAbogadoTipoabogados(Set abogadoTipoabogados) {
        this.abogadoTipoabogados = abogadoTipoabogados;
    }
    

    public List<Abogados> listaAbogados() {
        return dao.findAllAbogados();
    }

    public boolean GuardarAbogados(Abogados entidad) {
        return dao.Crearabogados(entidad);
    }
}


