package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asuntojudicial generated by hbm2java
 */
@Entity
@Table(name="asuntojudicial"
    ,catalog="despachoabogados"
)
public class Asuntojudicial  implements java.io.Serializable {


     private Integer idAsuntoJudicial;
     private Tipoasunto tipoasunto;
     private String descripcion;
     private boolean activo;
     private Set asuntojuzgados = new HashSet(0);

    public Asuntojudicial() {
    }

	
    public Asuntojudicial(Tipoasunto tipoasunto, String descripcion, boolean activo) {
        this.tipoasunto = tipoasunto;
        this.descripcion = descripcion;
        this.activo = activo;
    }
    public Asuntojudicial(Tipoasunto tipoasunto, String descripcion, boolean activo, Set asuntojuzgados) {
       this.tipoasunto = tipoasunto;
       this.descripcion = descripcion;
       this.activo = activo;
       this.asuntojuzgados = asuntojuzgados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idAsuntoJudicial", unique=true, nullable=false)
    public Integer getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }
    
    public void setIdAsuntoJudicial(Integer idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idTipoAsunto", nullable=false)
    public Tipoasunto getTipoasunto() {
        return this.tipoasunto;
    }
    
    public void setTipoasunto(Tipoasunto tipoasunto) {
        this.tipoasunto = tipoasunto;
    }
    
    @Column(name="Descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="Activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="asuntojudicial")
    public Set getAsuntojuzgados() {
        return this.asuntojuzgados;
    }
    
    public void setAsuntojuzgados(Set asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }




}


