package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import Modelos.Juzgados;
import Modelos.Asuntojudicial;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asuntojuzgado generated by hbm2java
 */
@Entity
@Table(name="asuntojuzgado"
    ,catalog="despachoabogados"
)
public class Asuntojuzgado  implements java.io.Serializable {


     private AsuntojuzgadoId id;
     private Juzgados juzgados;
     private Asuntojudicial asuntojudicial;
     private boolean activo;
     private Set expedientes = new HashSet(0);

    public Asuntojuzgado() {
    }

	
    public Asuntojuzgado(AsuntojuzgadoId id, Juzgados juzgados, Asuntojudicial asuntojudicial, boolean activo) {
        this.id = id;
        this.juzgados = juzgados;
        this.asuntojudicial = asuntojudicial;
        this.activo = activo;
    }
    public Asuntojuzgado(AsuntojuzgadoId id, Juzgados juzgados, Asuntojudicial asuntojudicial, boolean activo, Set expedientes) {
       this.id = id;
       this.juzgados = juzgados;
       this.asuntojudicial = asuntojudicial;
       this.activo = activo;
       this.expedientes = expedientes;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="idAsuntoJudicial", column=@Column(name="idAsuntoJudicial", nullable=false) ), 
        @AttributeOverride(name="idJuzgados", column=@Column(name="idJuzgados", nullable=false) ) } )
    public AsuntojuzgadoId getId() {
        return this.id;
    }
    
    public void setId(AsuntojuzgadoId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idJuzgados", nullable=false, insertable=false, updatable=false)
    public Juzgados getJuzgados() {
        return this.juzgados;
    }
    
    public void setJuzgados(Juzgados juzgados) {
        this.juzgados = juzgados;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idAsuntoJudicial", nullable=false, insertable=false, updatable=false)
    public Asuntojudicial getAsuntojudicial() {
        return this.asuntojudicial;
    }
    
    public void setAsuntojudicial(Asuntojudicial asuntojudicial) {
        this.asuntojudicial = asuntojudicial;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="asuntojuzgado")
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }




}


