package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AsuntojuzgadoId generated by hbm2java
 */
@Embeddable
public class AsuntojuzgadoId  implements java.io.Serializable {


     private int idAsuntoJudicial;
     private int idJuzgados;

    public AsuntojuzgadoId() {
    }

    public AsuntojuzgadoId(int idAsuntoJudicial, int idJuzgados) {
       this.idAsuntoJudicial = idAsuntoJudicial;
       this.idJuzgados = idJuzgados;
    }
   

    @Column(name="idAsuntoJudicial", nullable=false)
    public int getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }
    
    public void setIdAsuntoJudicial(int idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }

    @Column(name="idJuzgados", nullable=false)
    public int getIdJuzgados() {
        return this.idJuzgados;
    }
    
    public void setIdJuzgados(int idJuzgados) {
        this.idJuzgados = idJuzgados;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AsuntojuzgadoId) ) return false;
		 AsuntojuzgadoId castOther = ( AsuntojuzgadoId ) other; 
         
		 return (this.getIdAsuntoJudicial()==castOther.getIdAsuntoJudicial())
 && (this.getIdJuzgados()==castOther.getIdJuzgados());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAsuntoJudicial();
         result = 37 * result + this.getIdJuzgados();
         return result;
   }   


}


