package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name="departamento"
    ,catalog="despachoabogados"
)
public class Departamento  implements java.io.Serializable {

     private Integer idDepartamento;
     private String nombreDepartamento;
     private Set juzgadoses = new HashSet(0);

    public Departamento() {
        idDepartamento=0;
    }

	
    public Departamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamento(String nombreDepartamento, Set juzgadoses) {
       this.nombreDepartamento = nombreDepartamento;
       this.juzgadoses = juzgadoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idDepartamento", unique=true, nullable=false)
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    
    @Column(name="NombreDepartamento", nullable=false, length=50)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="departamento")
    public Set getJuzgadoses() {
        return this.juzgadoses;
    }
    
    public void setJuzgadoses(Set juzgadoses) {
        this.juzgadoses = juzgadoses;
    }




}


