package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallesexpediente generated by hbm2java
 */
@Entity
@Table(name="detallesexpediente"
    ,catalog="despachoabogados"
)
public class Detallesexpediente  implements java.io.Serializable {


     private int idExpediente;
     private Expediente expediente;
     private AbogadoTipoabogado abogadoTipoabogado;
     //private PersonaTipopersona personaTipopersona;

    public Detallesexpediente() {
    }

    public Detallesexpediente(int idExpediente, Expediente expediente, AbogadoTipoabogado abogadoTipoabogado) {
       this.idExpediente = idExpediente;
       this.expediente = expediente;
       this.abogadoTipoabogado = abogadoTipoabogado;
       //this.personaTipopersona = personaTipopersona;
    }
   
     @Id 
    
    @Column(name="idExpediente", unique=true, nullable=false)
    public int getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(int idExpediente) {
        this.idExpediente = idExpediente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idExpediente", unique=true, nullable=false, insertable=false, updatable=false)
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idTipoAbogado", referencedColumnName="idTipoAbogado", nullable=false), 
        @JoinColumn(name="idAbogado", referencedColumnName="idAbogado", nullable=false) } )
    public AbogadoTipoabogado getAbogadoTipoabogado() {
        return this.abogadoTipoabogado;
    }
    
    public void setAbogadoTipoabogado(AbogadoTipoabogado abogadoTipoabogado) {
        this.abogadoTipoabogado = abogadoTipoabogado;
    }
}