package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallefactura generated by hbm2java
 */
@Entity
@Table(name="detallefactura"
    ,catalog="despachoabogados"
)
public class Detallefactura  implements java.io.Serializable {


     private int idFactura;
     private Factura factura;
     private String descripcion;
     private float costo;

    public Detallefactura() {
    }

    public Detallefactura(int idFactura, Factura factura, String descripcion, float costo) {
       this.idFactura = idFactura;
       this.factura = factura;
       this.descripcion = descripcion;
       this.costo = costo;
    }
   
     @Id 
    
    @Column(name="idFactura", unique=true, nullable=false)
    public int getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(int idFactura) {
        this.idFactura = idFactura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idFactura", unique=true, nullable=false, insertable=false, updatable=false)
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    
    @Column(name="costo", nullable=false, precision=12, scale=0)
    public float getCosto() {
        return this.costo;
    }
    
    public void setCosto(float costo) {
        this.costo = costo;
    }




}


