package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Estadoexpediente generated by hbm2java
 */
@Entity
@Table(name="estadoexpediente"
    ,catalog="despachoabogados"
)
public class Estadoexpediente  implements java.io.Serializable {


     private Integer idEstadoExpediente;
     private String descripcion;
     private Date fechaEstado;
     private Set expedientes = new HashSet(0);

    public Estadoexpediente() {
    }

	
    public Estadoexpediente(String descripcion, Date fechaEstado) {
        this.descripcion = descripcion;
        this.fechaEstado = fechaEstado;
    }
    public Estadoexpediente(String descripcion, Date fechaEstado, Set expedientes) {
       this.descripcion = descripcion;
       this.fechaEstado = fechaEstado;
       this.expedientes = expedientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idEstadoExpediente", unique=true, nullable=false)
    public Integer getIdEstadoExpediente() {
        return this.idEstadoExpediente;
    }
    
    public void setIdEstadoExpediente(Integer idEstadoExpediente) {
        this.idEstadoExpediente = idEstadoExpediente;
    }
    
    @Column(name="Descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="FechaEstado", nullable=false, length=19)
    public Date getFechaEstado() {
        return this.fechaEstado;
    }
    
    public void setFechaEstado(Date fechaEstado) {
        this.fechaEstado = fechaEstado;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="estadoexpediente")
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }




}


