package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Expediente generated by hbm2java
 */
@Entity
@Table(name="expediente"
    ,catalog="despachoabogados"
)
public class Expediente  implements java.io.Serializable {


     private Integer idExpediente;
     private Estadoexpediente estadoexpediente;
     private Usuarios usuarios;
     private Asuntojuzgado asuntojuzgado;
     private String descripcion;
     private Date fechaAlta;
     private Date fechaBaja;
     private int anio;
     private Set facturas = new HashSet(0);
     private Set detallesexpedientes = new HashSet(0);
     private Set estadoevolutivos = new HashSet(0);

    public Expediente() {
    }

	
    public Expediente(Estadoexpediente estadoexpediente, Usuarios usuarios, Asuntojuzgado asuntojuzgado, String descripcion, Date fechaAlta, Date fechaBaja, int anio) {
        this.estadoexpediente = estadoexpediente;
        this.usuarios = usuarios;
        this.asuntojuzgado = asuntojuzgado;
        this.descripcion = descripcion;
        this.fechaAlta = fechaAlta;
        this.fechaBaja = fechaBaja;
        this.anio = anio;
    }
    public Expediente(Estadoexpediente estadoexpediente, Usuarios usuarios, Asuntojuzgado asuntojuzgado, String descripcion, Date fechaAlta, Date fechaBaja, int anio, Set facturas, Set detallesexpedientes, Set estadoevolutivos) {
       this.estadoexpediente = estadoexpediente;
       this.usuarios = usuarios;
       this.asuntojuzgado = asuntojuzgado;
       this.descripcion = descripcion;
       this.fechaAlta = fechaAlta;
       this.fechaBaja = fechaBaja;
       this.anio = anio;
       this.facturas = facturas;
       this.detallesexpedientes = detallesexpedientes;
       this.estadoevolutivos = estadoevolutivos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idExpediente", unique=true, nullable=false)
    public Integer getIdExpediente() {
        return this.idExpediente;
    }
    
    public void setIdExpediente(Integer idExpediente) {
        this.idExpediente = idExpediente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEstadoExpediente", nullable=false)
    public Estadoexpediente getEstadoexpediente() {
        return this.estadoexpediente;
    }
    
    public void setEstadoexpediente(Estadoexpediente estadoexpediente) {
        this.estadoexpediente = estadoexpediente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuarios", nullable=false)
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idAsuntoJudicial", referencedColumnName="idAsuntoJudicial", nullable=false), 
        @JoinColumn(name="idJuzgados", referencedColumnName="idJuzgados", nullable=false) } )
    public Asuntojuzgado getAsuntojuzgado() {
        return this.asuntojuzgado;
    }
    
    public void setAsuntojuzgado(Asuntojuzgado asuntojuzgado) {
        this.asuntojuzgado = asuntojuzgado;
    }
    
    @Column(name="Descripcion", nullable=false, length=500)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaAlta", nullable=false, length=10)
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaBaja", nullable=false, length=10)
    public Date getFechaBaja() {
        return this.fechaBaja;
    }
    
    public void setFechaBaja(Date fechaBaja) {
        this.fechaBaja = fechaBaja;
    }
    
    @Column(name="Anio", nullable=false)
    public int getAnio() {
        return this.anio;
    }
    
    public void setAnio(int anio) {
        this.anio = anio;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="expediente")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="expediente")
    public Set getDetallesexpedientes() {
        return this.detallesexpedientes;
    }
    
    public void setDetallesexpedientes(Set detallesexpedientes) {
        this.detallesexpedientes = detallesexpedientes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="expediente")
    public Set getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }




}


