package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name="factura"
    ,catalog="despachoabogados"
)
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Expediente expediente;
     private Personas personas;
     private Date fechaCreacion;
     private float subtotal;
     private float iva;
     private float total;
     private String medioPago;
     private String estado;
     private boolean activo;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(Expediente expediente, Personas personas, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo) {
        this.expediente = expediente;
        this.personas = personas;
        this.fechaCreacion = fechaCreacion;
        this.subtotal = subtotal;
        this.iva = iva;
        this.total = total;
        this.medioPago = medioPago;
        this.estado = estado;
        this.activo = activo;
    }
    public Factura(Expediente expediente, Personas personas, Date fechaCreacion, float subtotal, float iva, float total, String medioPago, String estado, boolean activo, Set detallefacturas) {
       this.expediente = expediente;
       this.personas = personas;
       this.fechaCreacion = fechaCreacion;
       this.subtotal = subtotal;
       this.iva = iva;
       this.total = total;
       this.medioPago = medioPago;
       this.estado = estado;
       this.activo = activo;
       this.detallefacturas = detallefacturas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idFactura", unique=true, nullable=false)
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idExpediente", nullable=false)
    public Expediente getExpediente() {
        return this.expediente;
    }
    
    public void setExpediente(Expediente expediente) {
        this.expediente = expediente;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPersona", nullable=false)
    public Personas getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Personas personas) {
        this.personas = personas;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="fechaCreacion", nullable=false, length=10)
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    
    @Column(name="subtotal", nullable=false, precision=12, scale=0)
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    
    @Column(name="iva", nullable=false, precision=12, scale=0)
    public float getIva() {
        return this.iva;
    }
    
    public void setIva(float iva) {
        this.iva = iva;
    }
    
    @Column(name="total", nullable=false, precision=12, scale=0)
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    
    @Column(name="medioPago", nullable=false, length=30)
    public String getMedioPago() {
        return this.medioPago;
    }
    
    public void setMedioPago(String medioPago) {
        this.medioPago = medioPago;
    }
    
    @Column(name="estado", nullable=false, length=30)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    
    @Column(name="Activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="factura")
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


