package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import DAO.Despachos.Personas.PersonasDAO;
import DAO.Despachos.Personas.PersonasDAOimpl;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Personas generated by hbm2java
 */
@Entity
@Table(name="personas"
    ,catalog="despachoabogados"
)
public class Personas  implements java.io.Serializable {


     private Integer idPersona;
     private String nombrePersona;
     private String primerApellidoPersona;
     private String segundoApellidoPersona;
     private String cedulaPersona;
     private String direccionPersona;
     private int telefonoPersona;
     private int celularPersona;
     private String emailPersona;
     private String observaciones;
     private Set facturas = new HashSet(0);
     private Set personaTipopersonas = new HashSet(0);
     private PersonasDAO dao;

    public Personas() {
        idPersona = 0; 
        dao = new PersonasDAOimpl();
    }

    public Personas(Integer idPersona, String nombrePersona, String primerApellidoPersona, String segundoApellidoPersona, String cedulaPersona, String direccionPersona, int telefonoPersona, int celularPersona, String emailPersona, String observaciones, Set tipoPersona) {
        this.idPersona = idPersona;
        this.nombrePersona = nombrePersona;
        this.primerApellidoPersona = primerApellidoPersona;
        this.segundoApellidoPersona = segundoApellidoPersona;
        this.cedulaPersona = cedulaPersona;
        this.direccionPersona = direccionPersona;
        this.telefonoPersona = telefonoPersona;
        this.celularPersona = celularPersona;
        this.emailPersona = emailPersona;
        this.observaciones = observaciones;
        this.personaTipopersonas = tipoPersona;
    }
	
    public Personas(String nombrePersona, String primerApellidoPersona, String cedulaPersona, String direccionPersona, int telefonoPersona, int celularPersona, String emailPersona) {
        this.nombrePersona = nombrePersona;
        this.primerApellidoPersona = primerApellidoPersona;
        this.cedulaPersona = cedulaPersona;
        this.direccionPersona = direccionPersona;
        this.telefonoPersona = telefonoPersona;
        this.celularPersona = celularPersona;
        this.emailPersona = emailPersona;
    }
    public Personas(String nombrePersona, String primerApellidoPersona, String segundoApellidoPersona, String cedulaPersona, String direccionPersona, int telefonoPersona, int celularPersona, String emailPersona, String observaciones, Set facturas, Set personaTipopersonas) {
       this.nombrePersona = nombrePersona;
       this.primerApellidoPersona = primerApellidoPersona;
       this.segundoApellidoPersona = segundoApellidoPersona;
       this.cedulaPersona = cedulaPersona;
       this.direccionPersona = direccionPersona;
       this.telefonoPersona = telefonoPersona;
       this.celularPersona = celularPersona;
       this.emailPersona = emailPersona;
       this.observaciones = observaciones;
       this.facturas = facturas;
       this.personaTipopersonas = personaTipopersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idPersona", unique=true, nullable=false)
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    
    @Column(name="nombrePersona", nullable=false, length=35)
    public String getNombrePersona() {
        return this.nombrePersona;
    }
    
    public void setNombrePersona(String nombrePersona) {
        this.nombrePersona = nombrePersona;
    }
    
    @Column(name="primerApellidoPersona", nullable=false, length=35)
    public String getPrimerApellidoPersona() {
        return this.primerApellidoPersona;
    }
    
    public void setPrimerApellidoPersona(String primerApellidoPersona) {
        this.primerApellidoPersona = primerApellidoPersona;
    }
    
    @Column(name="segundoApellidoPersona", length=35)
    public String getSegundoApellidoPersona() {
        return this.segundoApellidoPersona;
    }
    
    public void setSegundoApellidoPersona(String segundoApellidoPersona) {
        this.segundoApellidoPersona = segundoApellidoPersona;
    }
    
    @Column(name="cedulaPersona", nullable=false, length=16)
    public String getCedulaPersona() {
        return this.cedulaPersona;
    }
    
    public void setCedulaPersona(String cedulaPersona) {
        this.cedulaPersona = cedulaPersona;
    }
    
    @Column(name="direccionPersona", nullable=false, length=100)
    public String getDireccionPersona() {
        return this.direccionPersona;
    }
    
    public void setDireccionPersona(String direccionPersona) {
        this.direccionPersona = direccionPersona;
    }
    
    @Column(name="telefonoPersona", nullable=false)
    public int getTelefonoPersona() {
        return this.telefonoPersona;
    }
    
    public void setTelefonoPersona(int telefonoPersona) {
        this.telefonoPersona = telefonoPersona;
    }
    
    @Column(name="celularPersona", nullable=false)
    public int getCelularPersona() {
        return this.celularPersona;
    }
    
    public void setCelularPersona(int celularPersona) {
        this.celularPersona = celularPersona;
    }
    
    @Column(name="emailPersona", nullable=false, length=45)
    public String getEmailPersona() {
        return this.emailPersona;
    }
    
    public void setEmailPersona(String emailPersona) {
        this.emailPersona = emailPersona;
    }
    
    @Column(name="observaciones", length=100)
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="personas")
    public Set getPersonaTipopersonas() {
        return this.personaTipopersonas;
    }
    
    public void setPersonaTipopersonas(Set personaTipopersonas) {
        this.personaTipopersonas = personaTipopersonas;
    }

    public List<Personas> listaPersonas(){
        return dao.findAllPersons();
    }
    
    public boolean GuardarPersona(Personas entidad){
        return dao.CreatePersons(entidad);
    }

}


