package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoabogado generated by hbm2java
 */
@Entity
@Table(name="tipoabogado"
    ,catalog="despachoabogados"
)
public class Tipoabogado  implements java.io.Serializable {


     private Integer idTipoAbogado;
     private String descripcion;
     private Set abogadoTipoabogados = new HashSet(0);

    public Tipoabogado() {
        idTipoAbogado = 0;
    }

	
    public Tipoabogado(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipoabogado(String descripcion, Set abogadoTipoabogados) {
       this.descripcion = descripcion;
       this.abogadoTipoabogados = abogadoTipoabogados;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idTipoAbogado", unique=true, nullable=false)
    public Integer getIdTipoAbogado() {
        return this.idTipoAbogado;
    }
    
    public void setIdTipoAbogado(Integer idTipoAbogado) {
        this.idTipoAbogado = idTipoAbogado;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipoabogado")
    public Set getAbogadoTipoabogados() {
        return this.abogadoTipoabogados;
    }
    
    public void setAbogadoTipoabogados(Set abogadoTipoabogados) {
        this.abogadoTipoabogados = abogadoTipoabogados;
    }




}


