package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipopersona generated by hbm2java
 */
@Entity
@Table(name="tipopersona"
    ,catalog="despachoabogados"
)
public class Tipopersona  implements java.io.Serializable {


     private Integer idTipoPersona;
     private String descripcion;
     private Set personaTipopersonas = new HashSet(0);

    public Tipopersona() {
    }

	
    public Tipopersona(String descripcion) {
        this.descripcion = descripcion;
    }
    public Tipopersona(String descripcion, Set personaTipopersonas) {
       this.descripcion = descripcion;
       this.personaTipopersonas = personaTipopersonas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idTipoPersona", unique=true, nullable=false)
    public Integer getIdTipoPersona() {
        return this.idTipoPersona;
    }
    
    public void setIdTipoPersona(Integer idTipoPersona) {
        this.idTipoPersona = idTipoPersona;
    }
    
    @Column(name="descripcion", nullable=false, length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="tipopersona")
    public Set getPersonaTipopersonas() {
        return this.personaTipopersonas;
    }
    
    public void setPersonaTipopersonas(Set personaTipopersonas) {
        this.personaTipopersonas = personaTipopersonas;
    }




}


