package Entidades;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name="usuarios"
    ,catalog="despachoabogados"
)
public class Usuarios  implements java.io.Serializable {


     private Integer idUsuarios;
     private String alias;
     private String contrasena;
     private boolean activo;
     private Set estadoevolutivos = new HashSet(0);
     private Set expedientes = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String alias, String contrasena, boolean activo) {
        this.alias = alias;
        this.contrasena = contrasena;
        this.activo = activo;
    }
    public Usuarios(String alias, String contrasena, boolean activo, Set estadoevolutivos, Set expedientes) {
       this.alias = alias;
       this.contrasena = contrasena;
       this.activo = activo;
       this.estadoevolutivos = estadoevolutivos;
       this.expedientes = expedientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="idUsuarios", unique=true, nullable=false)
    public Integer getIdUsuarios() {
        return this.idUsuarios;
    }
    
    public void setIdUsuarios(Integer idUsuarios) {
        this.idUsuarios = idUsuarios;
    }
    
    @Column(name="alias", nullable=false, length=45)
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    
    @Column(name="contrasena", nullable=false, length=20)
    public String getContrasena() {
        return this.contrasena;
    }
    
    public void setContrasena(String contrasena) {
        this.contrasena = contrasena;
    }
    
    @Column(name="activo", nullable=false)
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getEstadoevolutivos() {
        return this.estadoevolutivos;
    }
    
    public void setEstadoevolutivos(Set estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="usuarios")
    public Set getExpedientes() {
        return this.expedientes;
    }
    
    public void setExpedientes(Set expedientes) {
        this.expedientes = expedientes;
    }




}


