package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import DAO.Despachos.Abogados.AbogadosDAO;
import DAO.Despachos.Abogados.AbogadosDAOimpl;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Abogados generated by hbm2java
 */
@Entity
@Table(name="abogados")
public class Abogados  implements java.io.Serializable {

     private Long idAbogado;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private String noCarne;
     private String cedula;
     private String direccion;
     private int telefono;
     private int celular;
     private String email;
     private boolean activo;
     private List<AbogadoTipoabogado> ata = new ArrayList<AbogadoTipoabogado>();
     private AbogadosDAO dao;

    public Abogados() {
        dao = new AbogadosDAOimpl();
    }

    public Abogados(Long idAbogado, String nombre, String primerApellido,String segundoApellido,
            String noCarne, String cedula, String direccion, int telefono,int celular, String email) {
        this.idAbogado = idAbogado;
        this.nombre = nombre;
        this.primerApellido = primerApellido;
        this.segundoApellido = segundoApellido;
        this.noCarne = noCarne;
        this.cedula = cedula;
        this.direccion = direccion;
        this.telefono = telefono;
        this.celular = celular;
        this.email = email;
    }

   
     @Id
     @GeneratedValue(strategy=GenerationType.IDENTITY)    
    @Column(name="idAbogado", unique=true, nullable=false)
    public Long getIdAbogado() {
        return idAbogado;
    }
    
    public void setIdAbogado(Long idAbogado) {
        this.idAbogado = idAbogado;
    }
    
    @Column(name= "nombre",unique=false, nullable=false, length=50)
    public String getNombre() {
        return nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    @Column(name="primerApellido", unique=false,nullable=false, length=50)
    public String getPrimerApellido() {
        return primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    
    @Column(name= "segundoApellido", unique=false, nullable = true, length = 50)
    public String getSegundoApellido() {
        return segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    
    @Column(name="noCarne", unique=false, nullable = true, length = 50)
    public String getNoCarne() {
        return noCarne;
    }
    
    public void setNoCarne(String noCarne) {
        this.noCarne = noCarne;
    }
    
    @Column(name="cedula", unique=false, nullable = true, length = 50)
    public String getCedula() {
        return cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }
    
    @Column(name="direccion", unique=false, nullable = true, length = 256)
    public String getDireccion() {
        return direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    
    @Column(name="telefono",unique=false, nullable = false)
    public int getTelefono() {
        return telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    
    @Column(name="celular",  unique=false, nullable = false)
    public int getCelular() {
        return celular;
    }
    
    public void setCelular(int celular) {
        this.celular = celular;
    }
    
    @Column(name="email", unique=false, nullable = true, length = 200 )
    public String getEmail() {
        return email;
    }
    
    public void setEmail(String email) {
        this.email = email;       
    }
    
    @Column(name="activo")
    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
@OneToMany(fetch = FetchType.LAZY, mappedBy = "id.abogados", cascade=CascadeType.ALL)
   
   public List<AbogadoTipoabogado> getata() {
        return ata;
    }

    public void setata(List<AbogadoTipoabogado> ata){
        this.ata = ata;
    }
           
    public List<Abogados> listaabogados(){
        return dao.findAllAbogados();
    }

    public boolean GuardarAbogados(Abogados entidad,Long idTipoAbogado, boolean Activo) {
        return dao.Crearabogados(entidad,idTipoAbogado,Activo);
    }

    public boolean actualizarAbogados(Abogados entidad,Long idTipoAbogado, boolean Activo) {
        return dao.actualizarabogados(entidad,idTipoAbogado,Activo);
    }
}


