package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * AsuntojuzgadoId generated by hbm2java
 */
@Embeddable
public class AsuntojuzgadoId implements java.io.Serializable {

    private Asuntojudicial asuntojudicial;
    private Juzgados juzgados;

    @ManyToOne
    public Asuntojudicial getAsuntojudicial() {
        return asuntojudicial;
    }

    public void setAsuntojudicial(Asuntojudicial asuntojudicial) {
        this.asuntojudicial = asuntojudicial;
    }

    @ManyToOne
    public Juzgados getJuzgados() {
        return juzgados;
    }

    public void setJuzgados(Juzgados juzgados) {
        this.juzgados = juzgados;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
 
        AsuntojuzgadoId that = (AsuntojuzgadoId) o;
 
        if (asuntojudicial != null ? !asuntojudicial.equals(that.asuntojudicial) : that.asuntojudicial != null) {
            return false;
        }
        if (juzgados != null ? !juzgados.equals(that.juzgados) : that.juzgados != null) {
            return false;
        }
 
        return true;
    }
 
    @Override
    public int hashCode() {
        int result;
        result = (asuntojudicial != null ? asuntojudicial.hashCode() : 0);
        result = 31 * result + (juzgados != null ? juzgados.hashCode() : 0);
        return result;
    }
    
}