package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import DAO.Despachos.AsuntosJudiciales.AsuntoJudicialDAO;
import DAO.Despachos.AsuntosJudiciales.AsuntoJudicialDAOimpl;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Asuntojudicial generated by hbm2java
 */
@Entity
@Table(name = "asuntojudicial")
public class Asuntojudicial implements java.io.Serializable {

    private Long idAsuntoJudicial;
    private Tipoasunto tipoasunto;
    private String descripcion;
    private boolean activo;
    private List<Asuntojuzgado> asuntojuzgados = new ArrayList<Asuntojuzgado>();
    private AsuntoJudicialDAO dao;

    public Asuntojudicial() {
        dao = new AsuntoJudicialDAOimpl();
        tipoasunto = new Tipoasunto();
    }

    public Asuntojudicial(Tipoasunto tipoasunto, String descripcion, boolean activo) {
        this.tipoasunto = tipoasunto;
        this.descripcion = descripcion;
        this.activo = activo;
    }

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    @Column(name = "idAsuntoJudicial", unique = true, nullable = false)
    public Long getIdAsuntoJudicial() {
        return this.idAsuntoJudicial;
    }

    public void setIdAsuntoJudicial(Long idAsuntoJudicial) {
        this.idAsuntoJudicial = idAsuntoJudicial;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idTipoAsunto", nullable = false)
    public Tipoasunto getTipoasunto() {
        return this.tipoasunto;
    }

    public void setTipoasunto(Tipoasunto tipoasunto) {
        this.tipoasunto = tipoasunto;
    }

    @Column(name = "Descripcion", nullable = false, length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "Activo", nullable = false)
    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ids.asuntojudicial", cascade=CascadeType.ALL)
    public List<Asuntojuzgado> getAsuntojuzgados() {
        return asuntojuzgados;
    }

    public void setAsuntojuzgados(List<Asuntojuzgado> asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }

    public List<Asuntojudicial> listaAsunto() {
        return dao.listaAsuntos();
    }

    public boolean guardarAsunto(Asuntojudicial entidadAsunto) {
        return dao.guardarAsunto(entidadAsunto);
    }

    public boolean actualizarAsunto(Asuntojudicial entidadAsunto) {
        return dao.actualizarAsunto(entidadAsunto);
    }
}
