package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA


import javax.persistence.Embeddable;
import javax.persistence.ManyToOne;

/**
 * AbogadoTipoabogadoId generated by hbm2java
 */
@Embeddable
public class ataId  implements java.io.Serializable {

    private Abogados abogados;
    private Tipoabogado tipoAbogado;

    @ManyToOne
    public Abogados getAbogados() {
        return abogados;
    }

    public void setAbogados(Abogados abogados) {
        this.abogados = abogados;
    }

    @ManyToOne
    public Tipoabogado getTipoAbogado() {
        return tipoAbogado;
    }

    public void setTipoAbogado(Tipoabogado tipoAbogado) {
        this.tipoAbogado = tipoAbogado;
    }
    
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
 
        ataId that = (ataId) o;
 
        if (abogados != null ? !abogados.equals(that.abogados) : that.abogados != null) {
            return false;
        }
        if (tipoAbogado != null ? !tipoAbogado.equals(that.tipoAbogado) : that.tipoAbogado != null) {
            return false;
        }
 
        return true;
    }
 
    @Override
    public int hashCode() {
        int result;
        result = (abogados != null ? abogados.hashCode() : 0);
        result = 31 * result + (tipoAbogado != null ? tipoAbogado.hashCode() : 0);
        return result;
    }
}


