package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento")
public class Departamento implements java.io.Serializable {

    private Long idDepartamento;
    private String nombreDepartamento;
    private List<Juzgados> juzgados = new ArrayList<Juzgados>();

    public Departamento() {
        idDepartamento = 0L;
    }

    public Departamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idDepartamento", unique = true, nullable = false)
    public Long getIdDepartamento() {
        return this.idDepartamento;
    }

    public void setIdDepartamento(Long idDepartamento) {
        this.idDepartamento = idDepartamento;
    }

    @Column(name = "NombreDepartamento", nullable = false, length = 50)
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }

    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "departamento")
    public List<Juzgados> getJuzgadoses() {
        return juzgados;
    }

    public void setJuzgadoses(List<Juzgados> juzgados) {
        this.juzgados = juzgados;
    }
}
