package Modelos;
// Generated 09-09-2013 12:06:13 AM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Estado generated by hbm2java
 */
@Entity
@Table(name = "estado")
public class Estado implements java.io.Serializable {

    private Long idEstado;
    private String descripcion;
    private List<Estadoexpediente> estadoexpedientes = new ArrayList<Estadoexpediente>();

    public Estado() {
    }

    public Estado(String descripcion) {
        this.descripcion = descripcion;
    }

    public Estado(String descripcion, List<Estadoexpediente> estadoexpedientes) {
        this.descripcion = descripcion;
        this.estadoexpedientes = estadoexpedientes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idEstado", unique = true, nullable = false)
    public Long getIdEstado() {
        return this.idEstado;
    }

    public void setIdEstado(Long idEstado) {
        this.idEstado = idEstado;
    }

    @Column(name = "Descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "estado")
    public List<Estadoexpediente> getEstadoexpedientes() {
        return this.estadoexpedientes;
    }

    public void setEstadoexpedientes(List<Estadoexpediente> estadoexpedientes) {
        this.estadoexpedientes = estadoexpedientes;
    }
}
