package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import DAO.Despachos.Juzgados.JuzgadosDAO;
import DAO.Despachos.Juzgados.JuzgadosDAOimpl;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Juzgados generated by hbm2java
 */
@Entity
@Table(name = "juzgados")
public class Juzgados implements java.io.Serializable {

    private Long idJuzgados;
    private Departamento departamento;
    private String descripcion;
    private String direccion;
    private int telefono;
    private int celular;
    private List<Asuntojuzgado> asuntojuzgados = new ArrayList<Asuntojuzgado>();
    private JuzgadosDAO dao;

    public Juzgados() {
        dao = new JuzgadosDAOimpl();
        departamento = new Departamento();
    }

    public Juzgados(Departamento departamento, String descripcion, String direccion, int telefono) {
        this.departamento = departamento;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.telefono = telefono;
    }

    public Juzgados(Departamento departamento, String descripcion, String direccion, int telefono, Integer celular) {
        this.departamento = departamento;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.telefono = telefono;
        this.celular = celular;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idJuzgados", unique = true, nullable = false)
    public Long getIdJuzgados() {
        return this.idJuzgados;
    }

    public void setIdJuzgados(Long idJuzgados) {
        this.idJuzgados = idJuzgados;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "idDepartamento", nullable = false)
    public Departamento getDepartamento() {
        return this.departamento;
    }

    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }

    @Column(name = "descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "direccion", nullable = false, length = 100)
    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    @Column(name = "telefono", nullable = false)
    public int getTelefono() {
        return this.telefono;
    }

    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }

    @Column(name = "celular")
    public int getCelular() {
        return this.celular;
    }

    public void setCelular(int celular) {
        this.celular = celular;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ids.juzgados", cascade=CascadeType.ALL)
    public List<Asuntojuzgado> getAsuntojuzgados() {
        return asuntojuzgados;
    }

    public void setAsuntojuzgados(List<Asuntojuzgado> asuntojuzgados) {
        this.asuntojuzgados = asuntojuzgados;
    }

    
    public List<Juzgados> listaJuzgados() {
        return dao.listaJuzgados();
    }

    public boolean GuardarJuzgados(Juzgados entidad) {
        return dao.CrearJuzgados(entidad);
    }
}
