package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.List;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoaviso generated by hbm2java
 */
@Entity
@Table(name = "tipoaviso")
public class Tipoaviso implements java.io.Serializable {

    private Long idTipoAviso;
    private String descripcion;
    private List<Estadoevolutivo> estadoevolutivos = new ArrayList<Estadoevolutivo>();

    public Tipoaviso() {
    }

    public Tipoaviso(String descripcion) {
        this.descripcion = descripcion;
    }

    public Tipoaviso(String descripcion, List estadoevolutivos) {
        this.descripcion = descripcion;
        this.estadoevolutivos = estadoevolutivos;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idTipoAviso", unique = true, nullable = false)
    public Long getIdTipoAviso() {
        return this.idTipoAviso;
    }

    public void setIdTipoAviso(Long idTipoAviso) {
        this.idTipoAviso = idTipoAviso;
    }

    @Column(name = "Descripcion", nullable = false, length = 45)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tipoaviso")
    public List<Estadoevolutivo> getEstadoevolutivos() {
        return this.estadoevolutivos;
    }

    public void setEstadoevolutivos(List<Estadoevolutivo> estadoevolutivos) {
        this.estadoevolutivos = estadoevolutivos;
    }
}
