package Modelos;
// Generated 09-06-2013 07:53:46 PM by Hibernate Tools 3.2.1.GA

import DAO.Despachos.AsuntosJudiciales.TipoAsuntoDAO;
import DAO.Despachos.AsuntosJudiciales.TipoAsuntoDAOimpl;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipoasunto generated by hbm2java
 */
@Entity
@Table(name = "tipoasunto")
public class Tipoasunto implements java.io.Serializable {

    private Long idTipoAsunto;
    private String descripcion;
    private boolean activo;
    private List<Asuntojudicial> asuntojudiciales = new ArrayList<Asuntojudicial>();
    private TipoAsuntoDAO dao;

    public Tipoasunto() {
        dao = new TipoAsuntoDAOimpl();
        idTipoAsunto = 0L;
    }

    public Tipoasunto(String descripcion, boolean activo) {
        this.descripcion = descripcion;
        this.activo = activo;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "idTipoAsunto", unique = true, nullable = false)
    public Long getIdTipoAsunto() {
        return this.idTipoAsunto;
    }

    public void setIdTipoAsunto(Long idTipoAsunto) {
        this.idTipoAsunto = idTipoAsunto;
    }

    @Column(name = "Descripcion", nullable = false, length = 50)
    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Column(name = "Activo", nullable = false)
    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "tipoasunto")
    public List<Asuntojudicial> getAsuntojudiciales() {
        return asuntojudiciales;
    }

    public void setAsuntojudiciales(List<Asuntojudicial> asuntojudiciales) {
        this.asuntojudiciales = asuntojudiciales;
    }

    public boolean guardarTipoAsunto(Tipoasunto entidad) {
        return dao.guardarTipoAsunto(entidad);
    }

    public List<Tipoasunto> listaTipoAsunto() {
        return dao.findAllTipoAsunto();
    }

    public boolean actualizarTipoAsunto(Tipoasunto entidad) {
        return dao.actualizarTipoAsunto(entidad);
    }
}
